
server:
  port: 8082
  servlet:
    context-path: /inventory

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
      lease:
        duration: 5

spring:
  application:
    name: inventory-service
